repos:
    -   repo: https://github.com/PyCQA/flake8
        rev: 7.1.2
        hooks:
            -   id: flake8
                additional_dependencies: [flake8-docstrings, flake8-blind-except, flake8-blind-except==0.2.1,
flake8-broken-line,
flake8-bugbear,
flake8-builtins,
flake8-class-attributes-order,
flake8-cognitive-complexity,
flake8-commas,
flake8-comprehensions,
flake8-debugger,
flake8-eradicate,
flake8-functions,
flake8-isort,
flake8-mutable,
flake8-print,
flake8-pytest,
flake8-pytest-style,
flake8-quotes,
flake8-string-format,
flake8-variables-names ]